
/* Drop Tables */

DROP TABLE USER_INFO CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE USER_INFO
(
	UI_NUM_NUMBER_PRIMARY_KEY number(10,0),
	UI_NAME_VARCHAR2 varchar2(100) NOT NULL,
	UI_AGE_NUMBER number(3,0) NOT NULL
);

INSERT INTO BOARD(UI_NUM_NUMBER_PRIMARY_KEY,UI_NAME_VARCHAR2,UI_AGE_NUMBER)
VALUES(1,'홍길동',20);

